/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio;

import javax.swing.JOptionPane;

/**
 *
 * @author lombardim
 */
public class Formulario extends javax.swing.JFrame {
    Boolean sw;
    E Ex;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        Ex = new E();
        initComponents();
        campoT.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                teclaPresionada(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleL = new javax.swing.JLabel();
        numerosB = new javax.swing.JButton();
        letrasB = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        mensajeL = new javax.swing.JLabel();
        campoT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(339, 190));
        setPreferredSize(new java.awt.Dimension(339, 190));
        setSize(new java.awt.Dimension(339, 190));
        getContentPane().setLayout(null);

        titleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleL.setText("¿Escribirá números o letras?");
        getContentPane().add(titleL);
        titleL.setBounds(10, 11, 319, 14);

        numerosB.setText("NÚMEROS");
        numerosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosBActionPerformed(evt);
            }
        });
        getContentPane().add(numerosB);
        numerosB.setBounds(20, 36, 120, 23);

        letrasB.setText("LETRAS");
        letrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letrasBActionPerformed(evt);
            }
        });
        getContentPane().add(letrasB);
        letrasB.setBounds(198, 36, 110, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 65, 339, 10);

        mensajeL.setVisible(false);
        mensajeL.setText(" ");
        getContentPane().add(mensajeL);
        mensajeL.setBounds(10, 81, 320, 14);

        campoT.setVisible(false);
        getContentPane().add(campoT);
        campoT.setBounds(10, 101, 305, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numerosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosBActionPerformed
        mensajeL.setText("Digite los números: ");
        mensajeL.setVisible(true);
        campoT.setVisible(true);
        campoT.setText("");
        sw = true;
    }//GEN-LAST:event_numerosBActionPerformed

    private void letrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letrasBActionPerformed
        mensajeL.setText("Digite las palabras: ");
        mensajeL.setVisible(true);
        campoT.setVisible(true);
        campoT.setText("");
        sw = false;
    }//GEN-LAST:event_letrasBActionPerformed
    private void teclaPresionada(java.awt.event.KeyEvent evt) {                                
        char k = evt.getKeyChar();
        String r = "" + k;
        if (!r.equals("\b")) {    
            int comp = comprobarBoton(k, sw);
            if (comp == 0) {
                evt.consume();
            }
        }
    }  
    public void comprobar() throws LabException{
        throw new LabException("No puede escribir la letra");
    }
    public int comprobarBoton(char c, Boolean b) {
        int comprobante = 0;
        String s = "" + c;
        if (b) {
                try {
                    Ex.comprobarNumNoLetras(isNumeric(s));
                    comprobante = 1;
                } catch (LabException e) {
                    JOptionPane.showMessageDialog(null,"Escribiste [ " + c + " ], solo debe escribir números", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
        }else{
            try {
                    Ex.comprobarLetrasNoNum(isNumeric(s));
                    comprobante = 1;
                } catch (LabException e) {
                    JOptionPane.showMessageDialog(null,"Escribiste el número [ " + c + " ], solo debe escribir letras.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
        }
        return comprobante;
    }
    
    public Boolean isNumeric(String S){
        try {
            Integer.parseInt(S);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoT;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton letrasB;
    private javax.swing.JLabel mensajeL;
    private javax.swing.JButton numerosB;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
